Automate removing whitespaces, and make 1 newline at EOF
pdffiller/styleguide-hooks pull request #27
Opened 2019-01-04 13:36 UTC by MaxymVlasov

Closed #13

2019-01-04 16:47 UTC, daimon243 submitted a review, later dismissed

2019-01-08 10:17 UTC, Haruhiist requested changes
Pls fix the only typo

2019-01-08 10:17 UTC, Haruhiist commented on README.md
> +After every `git clone` and `git checkout` the post checkout hook will create or recreate symlink to your hooks directory. [Documentation](https://git-scm.com/docs/githooks#_post_checkout).
post-checkout

2019-01-08 10:20 UTC, Haruhiist approved these changes

2019-01-08 10:20 UTC, merged